### PR TITLE
#167972368 ui feedback

### PR DESCRIPTION
**Pull request by Wabuluka**
#### What does this PR do?
Implements the feedback given to me by the LFA
#### Description of Task to be completed?
In this PR, 
* improved my responsiveness
* removed the black colour background in the navigation
* sign up form reduced to fewer requirements
* footer content centred
* made the signup and sign in page elegant
* add a picture on both login and signup pages
* centre the texts on the start pages
* put the signup and login pages on the same page
* added cards to display mentors available
* Added a button to relevant cards
* a mentor can accept or decline a request
#### How should this be manually tested?
After merging the PR, go to  https://wabuluka.github.io/FreeMentors/ui to test 
#### Screenshots (if appropriate)
fd1-2
FD1-4
fd1-5
fd1-6
FD1-33
fed1
fd2
fd2-1
fd3
one

### CODE REVIEW

**Comment by Oluwasegun-AA** [comment]
Please pt the signup and login buttons on the navigation bar
image

**Comment by Oluwasegun-AA** [comment]
you have made a good improvement on the UI. however, I want you to give it further facelift by taking the initiative to add some extra context to your UI. it seem to me the UI is dry and and scanty

**Comment by Wabuluka** [comment]
> Please pt the signup and login buttons on the navigation bar
> image

the links have been moved as directed

**Comment by Wabuluka** [comment]
> you have made a good improvement on the UI. however, I want you to give it further facelift by taking the initiative to add some extra context to your UI. it seem to me the UI is dry and and scanty
I have added the content as directed 
https://user-images.githubusercontent.com/17998079/64181368-01e53100-ce6f-11e9-8c8b-8fc7eb9569bd.PNG

**Comment by Wabuluka** [comment]
https://user-images.githubusercontent.com/17998079/64226845-aefc8f80-cee9-11e9-89d4-2406a68bb2f4.PNG

I have improved the signup login page to look like this

**Pull request merged**
